[install]
minimumReleaseAge = 259200 # 3 days

[install.security]
scanner = "@socketsecurity/bun-security-scanner"

# Packages that bypass the gate
minimumReleaseAgeExcludes = ["@taraxvoid/voidflow", "@types/bun", "bun-types","typescript"]
